name: VanillaXC
version: '2.0.0'
main: com.vanillaXC.VanillaXC
api-version: '1.21'
authors: [ XiaoPao45 ]
description: 自定义聊天格式插件
commands:
  vvc:
    description: VanillaXC主命令
    usage: /vvc <command>
